### ISSUE TITLE
Building for Relative Paths

### ISSUE THREAD

**Issue by lvisei** [reearth/craco-cesium#10]
When use relative paths
package.json:
```
{
  "homepage": ".",
}
```
Use HtmlWebpackTagsPlugin copy cesium files to htmlTag，should be considered "homepage" field in package.json file or relative path is recommended

like "./cesium/Widgets/widgets.css"

**Comment by Luyonzhang1993** [comment]
How to set CRA after ejected.

**Comment by rot1024** [comment]
> Building for Relative Paths

I recognize that it is already supported. 

This is a part of `index.html` in build result when homepage field in package.json is set `.`:

```html
<link href="./cesium/Widgets/widgets.css" rel="stylesheet"></head><body><noscript>You need to enable JavaScript to run this app.</noscript><div id="root"></div><script src="./cesium/Cesium.js">
```

> How to set CRA after ejected.

Unfortunately there is no way for now.
