### ISSUE TITLE
Error running "craco start" command while using react-scripts 3.3.1

### ISSUE THREAD

**Issue by MMrj9** [reearth/craco-cesium#14]
I'm having this error, after upgrading react-scripts to the newest version (3.3.1).

> Error running html-webpack-tags-plugin, are you sure you have html-webpack-plugin before it in your webpack config's plugins?
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! aurora-frontend@0.1.0 start: `env-cmd -e development craco start`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the aurora-frontend@0.1.0 start script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
Any ideas on what might be the problem?

**Comment by rot1024** [comment]
Did you try regenerating yarn.lock?

```
rm yarn.lock
yarn
yarn start
```

**Comment by Etheryte** [comment]
Same problem with react-scripts 3.0.1, rebuilding the lock doesn't resolve the issue.
