### ISSUE TITLE
some confused

### ISSUE THREAD

**Issue by qdxkrs** [reearth/craco-cesium#2]
Thank you for your contribution to the cesium.
I want to use cesium and create-react-app without rewire it. react-app-rewired is a custom configuration tools for react.
Is it possible to use react-app-rewired to build the project?

**Comment by hphpwj** [comment]
The same to me.

**Comment by qdxkrs** [comment]
I think craco is better now,it's very easy to use after used over a period of time.
One wonders:how to partial loading cesium is regarded as a doubtful question.

**Comment by rot1024** [comment]
Unfortunately craco-cesium does not support react-app-rewired, but I will try to publish a plugin for react-app-rewired such as react-app-rewire-cesium if there is demand.
