### ISSUE TITLE
Error running html-webpack-include-assets-plugin

### ISSUE THREAD

**Issue by qdxkrs** [reearth/craco-cesium#6]
After upgrade to 1.1.0,Provisioning has encountered a problem,Important details are located below.
--------------------------------------------------------------------
yarn run v1.16.0
$ craco start
Error running html-webpack-include-assets-plugin, are you sure you have html-webpack-plugin before it in your webpack config's plugins?
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
---------------------------------------------------------------------
I hope that after this incident, something will be done about these.

**Comment by rot1024** [comment]
Hi, this error has been fixed and now new version v1.1.1 is available. Thank you for reporting.
